In [ ]:
#1

In [1]:
import numpy as np

# Одновимірний масив
natural_numbers = np.arange(1, 11)

# Виводимо значення
print(natural_numbers)

[ 1  2  3  4  5  6  7  8  9 10]


#2

In [2]:
# створюємо двовимірний масив розміром 3х3, заповнений нулями
matrix_3x3 = np.zeros((3, 3))
matrix_3x3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#3

In [3]:
# Створюємо масив розміром 5х5, заповнений випадковими цілими числами в діапазоні від 1 до 10
random_matrix_5x5 = np.random.randint(1, 11, size=(5, 5))

# Виводимо значення
print(random_matrix_5x5)

[[9 5 1 1 3]
 [5 6 6 4 6]
 [4 1 1 7 5]
 [5 1 3 3 7]
 [6 8 8 1 3]]


#4

In [4]:
# Створюємо масив розміром 4x4, заповнений випадковими дійсними числами в діапазоні від 0 до 1
random_matrix_4x4 = np.random.rand(4, 4)

# Виводимо значення
print(random_matrix_4x4)

[[0.45462626 0.77524332 0.99829786 0.07504627]
 [0.33741294 0.91964961 0.99282907 0.49526543]
 [0.58012054 0.72917054 0.2267668  0.42091203]
 [0.96361565 0.84010343 0.63361927 0.54755878]]


#5

In [5]:
# Створюємо два одновимірних масиви розміром 5, заповнені випадковими цілими числами в діапазоні від 1 до 10
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

# Виконуємо поелементні операції додавання, віднімання та множення
additional_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

# Виводимо значення
array1, array2, additional_result, subtraction_result, multiplication_result

(array([ 5,  3, 10,  5,  5]),
 array([8, 3, 6, 6, 2]),
 array([13,  6, 16, 11,  7]),
 array([-3,  0,  4, -1,  3]),
 array([40,  9, 60, 30, 10]))

#6

In [6]:
# Створюємо два вектори розміром 7, заповнені випадковими числами
vector1 = np.random.randint(1, 11, size=7)
vector2 = np.random.randint(1, 11, size=7)

# Обчислюємо їх скалярний добуток
dot_product = np.dot(vector1, vector2)

vector1, vector2, dot_product


(array([2, 3, 9, 9, 6, 2, 1]), array([ 2,  8,  1,  2,  4,  3, 10]), 95)

#7

In [9]:
# Створюємо дві матриці розміром 2x2 та 2x3, заповнені випадковими цілими числами в діапазоні від 1 до 10
matrix_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix_2x3 = np.random.randint(1, 11, size=(2, 3))

# Обчислюємо множення матриць
result_matrix = np.dot(matrix_2x2, matrix_2x3)

# Виводимо результат
print("Matrix 2x2:")
print(matrix_2x2)
print("\nMatrix 2x3:")
print(matrix_2x3)
print("\nResulting Matrix after Multiplication:")
print(result_matrix)

Matrix 2x2:
[[3 9]
 [1 8]]

Matrix 2x3:
[[ 2  1  5]
 [10  8  1]]

Resulting Matrix after Multiplication:
[[96 75 24]
 [82 65 13]]


#8

In [10]:
# Створюємо матрицю розміром 3x3, заповнену випадковими цілими числами в діапазоні від 1 до 10
matrix_3x3 = np.random.randint(1, 11, size=(3, 3))

# Знаходимо обернену матрицю
inverse_matrix = np.linalg.inv(matrix_3x3)

matrix_3x3, inverse_matrix

(array([[ 5,  4,  6],
        [ 1,  9, 10],
        [ 2,  8, 10]]),
 array([[ 0.33333333,  0.26666667, -0.46666667],
        [ 0.33333333,  1.26666667, -1.46666667],
        [-0.33333333, -1.06666667,  1.36666667]]))

#9

In [12]:
# Створюємо матрицю розміром 4x4, заповнену випадковими дійсними числами в діапазоні від 0 до 1
matrix_4x4 = np.random.rand(4, 4)

# Транспортуємо матрицю
transposed_matrix = matrix_4x4.T

# Виводимо результат
print("Original Matrix:")
print(matrix_4x4)
print("\nTransposed Matrix:")
print(transposed_matrix)

Original Matrix:
[[0.06386781 0.17919073 0.86127561 0.73831313]
 [0.53389481 0.40204621 0.89500103 0.84597801]
 [0.23147165 0.92092797 0.21757927 0.41514284]
 [0.50814076 0.57522737 0.36625574 0.66539272]]

Transposed Matrix:
[[0.06386781 0.53389481 0.23147165 0.50814076]
 [0.17919073 0.40204621 0.92092797 0.57522737]
 [0.86127561 0.89500103 0.21757927 0.36625574]
 [0.73831313 0.84597801 0.41514284 0.66539272]]


#10

In [6]:
import numpy as np

# Створюємо матрицю розміром 3x4, заповнену випадковими цілими числами в діапазоні від 1 до 10
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))

# Створюємо вектор розміром 4, заповнений випадковими цілими числами в діапазоні від 1 до 10
vector_4 = np.random.randint(1, 11, size=4)

# Обчислюємо результат множення матриці та вектора
result = np.dot(matrix_3x4, vector_4)

matrix_3x4, vector_4, result


(array([[ 1, 10,  4,  2],
        [ 4,  2,  6,  9],
        [ 8,  8,  2,  2]]),
 array([7, 2, 1, 2]),
 array([35, 56, 78]))

#11

In [10]:
# Створюємо матрицю розміром 2x3, заповнену випадковими дійсними числами в діапазоні від 0 до 1
matrix_2x3 = np.random.rand(2, 3)

# Створюємо вектор розміром 3, заповнений випадковими дійсними числами в діапазоні від 0 до 1
vector_3 = np.random.rand(3)

# Обчислюємо результат множення матриці та вектора
result = np.dot(matrix_2x3, vector_3)

# Виводимо результати
print("Matrix 2x3:")
print(matrix_2x3)
print("\nVector 3:")
print(vector_3)
print("\nResult of multication:")
print(result)

Matrix 2x3:
[[0.18726008 0.72194713 0.15259393]
 [0.88168729 0.3606117  0.02801565]]

Vector 3:
[0.85065175 0.23692191 0.33057072]

Result of multication:
[0.3807813  0.84470681]


#12

In [13]:
# Створюємо дві матриці розміром 2x2, заповнені випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Обчислюємо поелементне множення матриць
elementtwise_multiplication = matrix1 * matrix2

# Виводимо результати

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nElement-wise Multiplication:")
print(elementtwise_multiplication)

Matrix 1:
[[8 9]
 [6 9]]

Matrix 2:
[[7 3]
 [9 1]]

Element-wise Multiplication:
[[56 27]
 [54  9]]


#13

In [14]:
# Створюємо дві матриці розміром 2x2, заповнені випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Знаходимо добуток матриць
product_matrix = np.dot(matrix1, matrix2)

# Виводимо результати
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nProduct Matrix:")
print(product_matrix)

Matrix 1:
[[ 6  1]
 [10  7]]

Matrix 2:
[[ 3  4]
 [ 9 10]]

Product Matrix:
[[ 27  34]
 [ 93 110]]


#14

In [15]:
# Створюємо матрицю розміром 5x5, заповнену випадковими цілими числами в діапазоні від 1 до 100
matrix_5x5 = np.random.randint(1, 101, size=(5, 5))

# Знаходимо суму елементів матриці
sum_of_elements = np.sum(matrix_5x5)

# Виводимо результати
matrix_5x5, sum_of_elements


(array([[78, 30, 17, 48, 48],
        [75, 72, 39,  5, 39],
        [28, 99, 72, 68, 64],
        [87, 27,  7, 28, 74],
        [51, 81, 17,  6, 50]]),
 1210)

#15

In [16]:
# Створюємо дві матриці розміром 4x4, заповнені випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

# Обчислюємо різницю матриць
difference_matrix = matrix1 - matrix2

# Виводимо результати
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nDifference Matrix:")
print(difference_matrix)

Matrix 1:
[[ 4 10  4  3]
 [ 1  6  8  9]
 [ 9  2  4 10]
 [ 7 10  1  6]]

Matrix 2:
[[4 7 5 1]
 [3 5 3 4]
 [8 6 8 5]
 [7 7 1 4]]

Difference Matrix:
[[ 0  3 -1  2]
 [-2  1  5  5]
 [ 1 -4 -4  5]
 [ 0  3  0  2]]


#16

In [19]:
import numpy as np

# Створюємо матрицю розміром 3x3 з випадковими дійсними числами в діапазоні [0, 1]
matrix = np.random.rand(3, 3)

# Виводимо створену матрицю
print("Матриця:")
print(matrix)

# Знаходимо вектор-стовпчик, що містить суму елементів кожного рядка матриці
sum_vector = np.sum(matrix, axis=1, keepdims=True)

# Виводимо знайдений вектор-стовпчик
print("\nВектор-стовпчик із сумами рядків матриці:")
print(sum_vector)

Матриця:
[[0.8636276  0.47527869 0.58159633]
 [0.70812776 0.20633804 0.57875608]
 [0.54020224 0.5945574  0.49364383]]

Вектор-стовпчик із сумами рядків матриці:
[[1.92050262]
 [1.49322189]
 [1.62840347]]


#17

In [20]:
import numpy as np

# Створюємо матрицю розміром 3x4 з довільними цілими числами
matrix = np.random.randint(1, 10, size=(3, 4)) # Генеруємо цілі числа в діапазоні від 1 до 10

# Виводимо початкову матрицю
print("Матриця:")
print(matrix)

# Створюємо нову матрицю, що містить квадрати чисел поелементно
squared_matrix = np.square(matrix)

# Виводимо матрицю з квадратами чисел
print("\nМатриця з квадратами чисел:")
print(squared_matrix)

Матриця:
[[2 4 8 7]
 [4 7 1 1]
 [8 4 3 7]]

Матриця з квадратами чисел:
[[ 4 16 64 49]
 [16 49  1  1]
 [64 16  9 49]]


#18

In [21]:
# Створюємо вектор розміром 4 з випадковими цілими числами в діапазоні від 1 до 50
random_vector = np.random.randint(1, 51, size=4)
print("Випадковий вектор:")
print(random_vector)

# Обчислюємо квадратні корені кожного елемента вектора
sqrt_vector = np.sqrt(random_vector)
print("\nВектор з квадратними коренями:")
print(sqrt_vector)

Випадковий вектор:
[16 14 15 37]

Вектор з квадратними коренями:
[4.         3.74165739 3.87298335 6.08276253]
